// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package io.dzh.netty.z_proto;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.do.proto.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realname = 1;</code>
   */
  java.lang.String getRealname();
  /**
   * <code>string realname = 1;</code>
   */
  com.google.protobuf.ByteString
      getRealnameBytes();
}
