// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package io.dzh.netty.z_proto;

public interface StudentResponseListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.do.proto.StudentResponseList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .io.do.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<io.dzh.netty.z_proto.StudentResponse> 
      getStudentResponseList();
  /**
   * <code>repeated .io.do.proto.StudentResponse studentResponse = 1;</code>
   */
  io.dzh.netty.z_proto.StudentResponse getStudentResponse(int index);
  /**
   * <code>repeated .io.do.proto.StudentResponse studentResponse = 1;</code>
   */
  int getStudentResponseCount();
  /**
   * <code>repeated .io.do.proto.StudentResponse studentResponse = 1;</code>
   */
  java.util.List<? extends io.dzh.netty.z_proto.StudentResponseOrBuilder> 
      getStudentResponseOrBuilderList();
  /**
   * <code>repeated .io.do.proto.StudentResponse studentResponse = 1;</code>
   */
  io.dzh.netty.z_proto.StudentResponseOrBuilder getStudentResponseOrBuilder(
      int index);
}
