// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package io.dzh.netty.z_proto;

public interface StudentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.do.proto.StudentRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 age = 1;</code>
   */
  int getAge();
}
